Repository Thream/api, pull requests merged in 2020-11, with the labels that each got.

#32 Feature/Authentication with `discord` oauth2 provider
  .env.example
  .github/workflows/codeql-analysis.yml
  .github/workflows/commitlint.yml
  .github/workflows/nodejs.yml
  .gitignore
  README.md
  package-lock.json
  package.json
  src/controllers/Users/confirmEmail.ts
  src/controllers/Users/oauth2/discord.ts
  src/controllers/Users/utils/buildQueryURL.ts
  src/controllers/Users/utils/isValidRedirectURIValidation.ts
  src/middlewares/authenticateUser.ts
  src/models/User.ts
  src/routes/users.ts
  src/typings/global.d.ts
  src/utils/config/constants.ts
  src/utils/config/socket.ts
Labels: feature request

#36 chore: rewrite path to controllers in lowercase
  docs/guilds/controllers/public/getDiscover.yaml
  src/controllers/channels/__test__/deleteById.test.ts
  src/controllers/channels/__test__/get.test.ts
  src/controllers/channels/__test__/post.test.ts
  src/controllers/channels/__test__/putById.test.ts
  src/controllers/channels/__test__/utils/createChannel.ts
  src/controllers/channels/deleteById.ts
  src/controllers/channels/get.ts
  src/controllers/channels/post.ts
  src/controllers/channels/putById.ts
  src/controllers/guilds/__test__/deleteById.test.ts
  src/controllers/guilds/__test__/get.test.ts
  src/controllers/guilds/__test__/getById.test.ts
  src/controllers/guilds/__test__/getPublicDiscover.test.ts
  src/controllers/guilds/__test__/post.test.ts
  src/controllers/guilds/__test__/putById.test.ts
  src/controllers/guilds/__test__/utils/createGuild.ts
  src/controllers/guilds/deleteById.ts
  src/controllers/guilds/get.ts
  src/controllers/guilds/getById.ts
  src/controllers/guilds/post.ts
  src/controllers/guilds/public/getDiscover.ts
  src/controllers/guilds/putById.ts
  src/controllers/users/__test__/confirmEmail.test.ts
  src/controllers/users/__test__/current.test.ts
  src/controllers/users/__test__/refreshToken.test.ts
  src/controllers/users/__test__/resetPassword.test.ts
  src/controllers/users/__test__/signin.test.ts
  src/controllers/users/__test__/signout.test.ts
  src/controllers/users/__test__/signup.test.ts
  src/controllers/users/confirmEmail.ts
  src/controllers/users/current.ts
  src/controllers/users/oauth2/discord.ts
  src/controllers/users/refreshToken.ts
  src/controllers/users/resetPassword.ts
  src/controllers/users/signin.ts
  src/controllers/users/signout.ts
  src/controllers/users/signup.ts
  src/controllers/users/utils/buildQueryURL.ts
  src/controllers/users/utils/isValidRedirectURIValidation.ts
  src/controllers/users/utils/sendConfirmEmail.ts
  src/routes/channels.ts
  src/routes/guilds.ts
  src/routes/users.ts
Labels: improvement

#44 Continous Integration Improvements
  .editorconfig
  .github/workflows/codeql-analysis.yml
  .github/workflows/commitlint.yml
  .github/workflows/nodejs.yml
  package-lock.json
  package.json
Labels: dependencies, github_actions
